#!/usr/bin/env python3
"""Generate src/unicode_width_table.h from the Unicode data files.

Inputs (download from https://www.unicode.org/Public/UCD/latest/ucd/):
  - EastAsianWidth.txt   -> code points with width W or F become "wide" (2)
  - UnicodeData.txt      -> general categories Mn, Me become "zero" (0),
                            plus the zero-width format controls listed below.

Usage:
  python3 scripts/gen_unicode_width.py EastAsianWidth.txt UnicodeData.txt \
      > src/unicode_width_table.h

This regenerates the curated table shipped in the repository with a complete,
authoritative one. Keep the output sorted and non-overlapping (the C side
binary-searches it).
"""

import sys

# Zero-width format controls (Cf) that should render as 0 cells even though
# their general category is not Mn/Me.
ZERO_WIDTH_CF = [
    (0x200B, 0x200F), (0x202A, 0x202E), (0x2060, 0x2064),
    (0x206A, 0x206F), (0xFEFF, 0xFEFF), (0xFFF9, 0xFFFB),
    (0xE0001, 0xE0001), (0xE0020, 0xE007F),
]


def parse_east_asian_width(path):
    wide = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            field, _, value = line.partition(";")
            value = value.strip()
            if value not in ("W", "F"):
                continue
            if ".." in field:
                lo, hi = field.split("..")
            else:
                lo = hi = field
            wide.append((int(lo, 16), int(hi, 16)))
    return wide


def parse_combining(path):
    zero = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            parts = line.split(";")
            if len(parts) < 3:
                continue
            cp = int(parts[0], 16)
            if parts[2] in ("Mn", "Me"):
                zero.append((cp, cp))
    return zero


def coalesce(ranges):
    ranges = sorted(ranges)
    out = []
    for lo, hi in ranges:
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def emit(name, ranges):
    print(f"static const proven_u32 {name}[][2] = {{")
    for lo, hi in ranges:
        print(f"    {{0x{lo:08X}, 0x{hi:08X}}},")
    print("};")
    print()


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    wide = coalesce(parse_east_asian_width(sys.argv[1]))
    zero = coalesce(parse_combining(sys.argv[2]) + ZERO_WIDTH_CF)

    print("#ifndef PROV_UNICODE_WIDTH_TABLE_H")
    print("#define PROV_UNICODE_WIDTH_TABLE_H")
    print()
    print('/* Generated by scripts/gen_unicode_width.py. Do not edit by hand. */')
    print()
    print('#include "proven/types.h"')
    print()
    emit("prov_width_zero", zero)
    emit("prov_width_wide", wide)
    print("#define PROV_WIDTH_ZERO_COUNT "
          "(sizeof(prov_width_zero) / sizeof(prov_width_zero[0]))")
    print("#define PROV_WIDTH_WIDE_COUNT "
          "(sizeof(prov_width_wide) / sizeof(prov_width_wide[0]))")
    print()
    print("#endif /* PROV_UNICODE_WIDTH_TABLE_H */")


if __name__ == "__main__":
    main()
